# Notebook to join Custom $Values for export suitable for the Ottoneu Value Calculator

In [1]:
League_path = '/Users/cmartin/Fantasy_Baseball/Ottoneu_Baseball_Projects/Imaginary_Hammers/'

In [2]:
Proj_files = {
    'Hitter':'Latest_Hitter_Proj.csv',
    'Pitcher':'Latest_Pitcher_Proj.csv'
}

In [3]:
Player_ID_Map_Path = '/Users/cmartin/Fantasy_Baseball/Ottoneu_Baseball_Projects/Player_ID_Map/Latest_Player_ID_Map.csv'

In [4]:
import pandas as pd

In [5]:
Export_Cols = {
    'OTTONEUID':'otto',
    'FANGRAPHSNAME':'Name',
    'POS':'Pos',
    'TEAM':'Team',
    'TOTAL_SGP_Val':'$'
}

In [6]:
Player_ID_Map_df = pd.read_csv(Player_ID_Map_Path)

In [7]:
Hitter_Proj_df = pd.read_csv(League_path+Proj_files['Hitter'])
Pitcher_Proj_df = pd.read_csv(League_path+Proj_files['Pitcher'])

In [8]:
Hitter_Proj_df.head()

,PlayerId,MLBAMID,Name,Team,NameASCII,G,PA,AB,H,1B,...,HR_SGP_norm,OBP_SGP_norm,SLG_SGP_norm,TOTAL_SGP,TOTAL_SGP_Rank,TOTAL_SGP_Val,R_SGP_Val,HR_SGP_Val,OBP_SGP_Val,SLG_SGP_Val
0,10028,542194,Christian Bethancourt,CHC,Christian Bethancourt,0.0000,1.0000,1.0000,0.0000,0.00000,...,-1.078500,0.256092,0.249206,-2.399627,1061.5,-10.867145,-18.557397,-14.916590,11.417255,9.008911
1,10155,545361,Mike Trout,LAA,Mike Trout,129.1444,556.3820,472.4704,113.9432,65.56196,...,1.134775,0.683445,0.619305,3.143815,65.0,14.237334,7.176261,15.694918,30.469744,22.388146
2,10642,542208,Carlos Pérez,HOU,Carlos Perez,0.0000,1.0000,1.0000,0.0000,0.00000,...,-1.078500,0.256092,0.249206,-2.399627,1061.5,-10.867145,-18.557397,-14.916590,11.417255,9.008911
3,10815,595777,Jurickson Profar,ATL,Jurickson Profar,144.9268,627.0208,543.6880,134.1240,90.24152,...,0.204894,0.512535,-0.119218,1.353659,149.0,6.130292,7.675732,2.833863,22.850110,-4.309767
4,11477,592885,Christian Yelich,MIL,Christian Yelich,142.5496,612.5212,536.5336,137.0560,92.19288,...,0.461301,0.551906,0.117543,1.899641,119.0,8.602868,7.812306,6.380200,24.605402,4.249239

In [9]:
Player_ID_Map_df[Player_ID_Map_df['FANGRAPHSNAME'] == 'Mike Trout'].iloc[0]

IDPLAYER                                     troutmi01
PLAYERNAME                                  Mike Trout
BIRTHDATE                                     8/7/1991
FIRSTNAME                                         Mike
LASTNAME                                         Trout
TEAM                                               LAA
LG                                                  AL
POS                                                 OF
IDFANGRAPHS                                      10155
FANGRAPHSNAME                               Mike Trout
MLBID                                         545361.0
MLBNAME                                     Mike Trout
CBSID                                        1739608.0
CBSNAME                                     Mike Trout
RETROID                                       troum001
BREFID                                       troutmi01
NFBCID                                          7689.0
NFBCNAME                                    Mike Trout
ESPNID                                         30836.0
ESPNNAME                                    Mike Trout
KFFLNAME                                    Mike Trout
DAVENPORTID                             TROUT19910807A
BPID                                           59432.0
YAHOOID                                         8861.0
YAHOONAME                                   Mike Trout
MSTRBLLNAME                                Trout, Mike
BATS                                                 R
THROWS                                               R
FANTPROSNAME                                Mike Trout
LASTCOMMAFIRST                             Trout, Mike
ROTOWIREID                                     10956.0
FANDUELNAME                                 Mike Trout
FANDUELID                                      12933.0
DRAFTKINGSNAME                              Mike Trout
OTTONEUID                                       6305.0
HQID                                            3857.0
RAZZBALLNAME                                Mike Trout
FANTRAXID                                      *01s8u*
FANTRAXNAME                                 Mike Trout
ROTOWIRENAME                                Mike Trout
ALLPOS                                              OF
NFBCLASTFIRST                              Trout, Mike
ACTIVE                                               Y
UNDERDOG          e5a1a7f7-8096-4b6b-b3a6-c96bad3b9a7f
RAZZBALLID                                     10155.0
Name: 3429, dtype: object

In [10]:
Hitter_Proj_df.rename(columns={
    'PlayerId':'IDFANGRAPHS'
},inplace=True)
Pitcher_Proj_df.rename(columns={
    'PlayerId':'IDFANGRAPHS'
},inplace=True)

In [11]:
Hitter_merge = Hitter_Proj_df[['IDFANGRAPHS','TOTAL_SGP_Val']].merge(Player_ID_Map_df[['IDFANGRAPHS','OTTONEUID','POS','FANGRAPHSNAME','PLAYERNAME','TEAM']],how='inner')

In [12]:
Pitcher_merge = Pitcher_Proj_df[['IDFANGRAPHS','TOTAL_SGP_Val']].merge(Player_ID_Map_df[['IDFANGRAPHS','OTTONEUID','POS','FANGRAPHSNAME','PLAYERNAME','TEAM']],how='inner')

In [13]:
Hitter_merge[(Hitter_merge['FANGRAPHSNAME'].isna()) & (Hitter_merge['TOTAL_SGP_Val'] > -1.)]['TOTAL_SGP_Val'].count()

np.int64(0)

In [14]:
Pitcher_merge[(Pitcher_merge['FANGRAPHSNAME'].isna()) & (Pitcher_merge['TOTAL_SGP_Val'] > -1.)]['TOTAL_SGP_Val'].count()

np.int64(0)

In [15]:
Hitter_merge[(Hitter_merge['TOTAL_SGP_Val'] >= 1.)]['TOTAL_SGP_Val'].sum()

np.float64(2585.4651555459286)

In [16]:
Pitcher_merge[(Pitcher_merge['TOTAL_SGP_Val'] >= 1.)]['TOTAL_SGP_Val'].sum()

np.float64(2273.7558095376453)

In [17]:
Hitter_Pitcher = pd.concat(
    [
        Hitter_merge,
        Pitcher_merge
    ]
)

In [18]:
Hitter_Pitcher.head()

,IDFANGRAPHS,TOTAL_SGP_Val,OTTONEUID,POS,FANGRAPHSNAME,PLAYERNAME,TEAM
0,10028,-10.867145,18048.0,C,Christian Bethancourt,Christian Bethancourt,TOR
1,10155,14.237334,6305.0,OF,Mike Trout,Mike Trout,LAA
2,10642,-10.867145,9791.0,C,Carlos Perez,Carlos Perez,CHC
3,10815,6.130292,13702.0,OF,Jurickson Profar,Jurickson Profar,ATL
4,11477,8.602868,14893.0,OF,Christian Yelich,Christian Yelich,MIL

In [19]:
Final_df = Hitter_Pitcher.rename(columns=Export_Cols)[[val for key,val in Export_Cols.items()]]

In [20]:
Final_df.head()

      otto                   Name Pos Team          $
0  18048.0  Christian Bethancourt   C  TOR -10.867145
1   6305.0             Mike Trout  OF  LAA  14.237334
2   9791.0           Carlos Perez   C  CHC -10.867145
3  13702.0       Jurickson Profar  OF  ATL   6.130292
4  14893.0       Christian Yelich  OF  MIL   8.602868

In [21]:
Final_df.to_csv(League_path+'Ottoneu_Value_Calc_Custom$Values.csv',index=False)